### PR TITLE
Technical Assignment Test - HotelReview

### PR DESCRIPTION
**Pull request by kyawzawwin88**
Please accept the pull request and merge in order to see my code.

Thanks,
Win

### CODE REVIEW

**Comment by liakwee-mirum** [comment]
Cannot get my simulated geolocation in iOS simulator.

image

**Comment by kyawzawwin88** [comment]
Hi Liak,

    You need to assign geolocation if you use simulator.

     For ios, please follow this,

     Toolbar -> simulator -> location -> custom location -> set geolocation
latitude and longtitude coordinates.

     It should works fine. Otherwise, please try to use Ionic View with the
app id.

Thanks,
Win

**Comment by liakwee-mirum** [comment]
Yes, I've added the custom location but it is still default to bugis.
Ionic view, is also not getting my phone geolocation.

**Comment by kyawzawwin88** [comment]
I see. It is weird. For ionic view, can you please check whether location service is on? 

I am checking on the simulator at the moment.

Settings -> Ionic View -> Location on While using

**Comment by liakwee-mirum** [comment]
yes the location option for ionic view is set to `While Using`

**Comment by kyawzawwin88** [comment]
I see. And your GPS location service also on, right?

**Comment by liakwee-mirum** [comment]
Yes, is on and i can get phone geolocation for other apps

**Comment by kyawzawwin88** [comment]
I see. Let me check and get back to you

**Comment by liakwee-mirum** [comment]
Sure.

**Comment by kyawzawwin88** [comment]
I think there is some known issues with geolocation plugin which cause POSITION_UNAVAILABLE error. Could you please follow these steps?

1. go to the hotel-view source root
2. gulp -b
3. cordova platform remove ios
4. cordova platform add ios
5. and run it on simulator

It works for me. I will check issue on Ionic View

**Comment by kyawzawwin88** [comment]
Hi Liak Wee,

    Sorry, it is my bad. I've fix the issue and it should work fine now. For simulator, please pull latest source and recompile.

    For ionic view, please
    1. kill the app
    2. sync latest
    3. clear app data
    4. view app

Thanks,
Win

**Comment by kyawzawwin88** [comment]
Hi Liak Wee,

    Is everything Ok? Anything you want me to explain? Any feedback?

Thanks,
Win

**Pull request closed without merging**
